server:
  port: 8800

spring:
  jpa:
    hibernate:
      #     ???????????
      ddl-auto: update
      #    ?????SQL
    show-sql: true
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-otbn3asw.sql.tencentcdb.com:24019/api
    username: jimmy
    password: Password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  api-docs:
    enabled: true

logging:
  file:
    name: log/log.log
  level:
    root: info
    com.example: debug