server:
  port: 8800

spring:
  jpa:
    hibernate:
      #     ???????????
      ddl-auto: update
      #    ?????SQL
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/API?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: zrc1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  api-docs:
    enabled: true

logging:
  file:
    name: log/log.log
  level:
    root: info
    com.example: debug